owners:
  - You (or several people's) IDs
whitelisted:
  - Any whitelisted users
password: Bot password
mongodbserver: MongoDB server (legacy)
token: Bot Token
weatherapikey: OpenWeatherMap API Key
googleapikey: Google API Key
hypixelapikey: Hypixel API Key
githubkey: Github API key
nasakey: Nasa API Key
travitiakey: Travitia API Key
redditauth:
  - idk I forgot sorry
  - idk I forgot sorry
  - Reddit user agent
zanekey: Zane API Key
urbankey: RapidAPI Urban Dictionary Key